### ISSUE TITLE
Problemas al llegar a 60 segundos

### ISSUE THREAD

**Issue by zeratulmdq** [UTN-MDP/reloj#2]
Similar al #1 cuando la aguja del segundero pasa de 59 a 60 segundos, se ve un parpadeo como si girase hacia atrás la vuelta completa.

**Comment by zeratulmdq** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reloj - Problemas al minuto](https://trello.com/c/hwul3aqs/14-reloj-problemas-al-minuto)

**Comment by carlosdev833** [comment]
Lo hago yo

**Comment by zeratulmdq** [comment]
Cerrado gracias a #6
